### ISSUE TITLE
Missing node.contact / owner information

### ISSUE THREAD

**Issue by 1977er** [freifunk/meshviewer#96]
We migrated from https://github.com/ffrgb/meshviewer here. The other project showed contact information on each node owner. That was very helpful in many cases.

I think data protection considerations do not apply here, because sharing any information is optional for each node owner.

I do understand that some communities don't want this, therefore this should be configurable via a global toggle.

**Comment by belzebub40k** [comment]
Prior to the TypeScript migration there was a commented out section in the code which can also be found in the ffrgb fork. Looks like this feature got lost with the migration to using a config.json again instead of including the whole config in JavaScript code. As Yanic already has a toggle to exclude the contact information I also think it should always be displayed if the value is present in the meshviewer.json.

https://github.com/freifunk/meshviewer/blob/f87d3c2980bece4102c6f3c727610b4b67e92965/lib/config_default.js#L25

**Comment by 1977er** [comment]
It's actually `"name": "node.contact"`. Works perfectly. Thanks.
